os: osx
osx_image: xcode10.1
language: swift

branches:
  only:
    - master

cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage/Build

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

script:
  - ./Tools/ci.sh
